# Mest.JS config example
# db:
#   type: 'oracle'
#   name: 'FCBKP_IMB'
#   host: '10.131.1.211'
#   port: 1521
#   sid: 'FCIMBTESTE'
#   username: 'sfc'
#   password: 'sfc'
#   synchronize: false

db:
  user: 'sfc'
  password: 'sfc'
  host: 'FCBKP_CORP_NOVO'
  poolMin: 1
  poolMax: 4
  poolIncrement: 1
  poolTimeout: 4

jwt:
  secret: 'FCBKP_IMB_OKD'
